# Generated by Django 4.2.3 on 2023-08-04 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0003_city_country_venue_city_country_alter_event_venue"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="venue",
            name="country",
        ),
        migrations.AlterField(
            model_name="venue",
            name="city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="venues",
                to="events.city",
            ),
        ),
    ]
